open-gluck/opengluck-swift-app

OpenGluck Phone App/PhoneAppTabs.swift
OpenGluck Watch App/AddInsulinButton.swift
OpenGluck Watch App/AddLowButton.swift
OpenGluck Watch App/UI/DigiPadView.swift
OpenGluck Watch App/WatchContentView.swift
OpenGluck.xcodeproj/project.pbxproj
OpenGluck/Bricks/AddLowBrick.swift
OpenGluck/Bricks/Brick.swift
OpenGluck/OpenGluck/OpenGluckEnvironmentUpdater.swift
OpenGluck/Records/Glucose/CurrentGlucoseView.swift
OpenGluck/Records/Glucose/GlucoseGraph.swift
OpenGluck/Records/Glucose/GlucoseTrend.swift
OpenGluck/Records/Glucose/LastRecordsView.swift
OpenGluck/UI/CheckConnectionHasClient.swift
OpenGluck/UI/HoldButton.swift
OpenGluck/UI/SheetStatusView.swift
OpenGluck/Widgets/GraphWidget.swift

- Add button to send new insulin records from watchOS
- Add button to send new low records from watchOS
- Improve interface with watchOS 10 additions

Improve watchOS UI/UX, add Insulin and Snack buttons

---

OpenGluck.xcodeproj/project.pbxproj
OpenGluck/AppIntents/AppsShortcuts.swift
OpenGluck/AppIntents/OpenGluckAppIntents.swift
OpenGluck/AppIntents/Snippets/GlucoseRecordSnippet.swift
OpenGluck/Records/TimestampView.swift

Added two phrases:
- *what's my blood glucose in OpenGlück* (or *in OG*)
- *get OG* (for a super short shortcut)

Add Get current glucose app intent

---

OpenGluck/Records/Glucose/GlucoseGraph.swift

- Add support for “snoozed” low (low with 0g of sugar)
- Improve how we display lows

Add support for snoozed lows, improve low symbol

---

OpenGluck Watch App/AddLowButton.swift
OpenGluck Watch App/WatchContentView.swift

Add snack choice when adding sugar

---

OpenGluck Phone App/PhoneContentView.swift
OpenGluck.xcodeproj/project.pbxproj
OpenGluck.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
OpenGluck/Bricks/CurrentGlucoseBrick.swift
OpenGluck/Bricks/GlucoseTrendBrick.swift
OpenGluck/OpenGluck/OpenGluckConnection.swift
OpenGluck/OpenGluck/OpenGluckEnvironmentUpdater.swift
OpenGluck/OpenGluck/OpenGluckUI.swift
OpenGluck/Records/Glucose/CurrentDataGauge.swift
OpenGluck/Records/Glucose/CurrentGlucose.swift
OpenGluck/UI/LowIcon.swift
OpenGluck/Widgets/CurrentGlucoseWidget.swift
OpenGluck/Widgets/GraphWidget.swift

Add in-app badge showing current instant glucose on top of the current last glucose record

feat: add instant glucose

---

OpenGluck.xcodeproj/project.pbxproj
OpenGluck/UI/LowIcon.swift

feat: improve LowIcon

---

OpenGluck/Records/Glucose/GlucoseGraph.swift

Fix trend line when scan records update too often

fix: trend line

---

OpenGluck/Records/Glucose/GlucoseGraph.swift

fix: improve show snoozed lows in GlucoseGraph

---

OpenGluck/Records/Glucose/CurrentDataGauge.swift

Always shows current glucose even if still the same (using an arrow)

feat: improve rendering of instant glucose

---

OpenGluck/Records/Glucose/CurrentDataGauge.swift
OpenGluck/Widgets/CurrentGlucoseWidget.swift

fix: current glucose widget

---

OpenGluck/Bricks/GlucoseTrendBrick.swift

fix: glucose trend brick

---

OpenGluck/AppIntents/AppsShortcuts.swift

Add more sentances so that it's more natural to ask for the current blood glucose.

feat: add variations for reading current blood glucose with Siri

---

OpenGluck Watch App/AddLowButton.swift

Add a new button in `AddLowButtonMulti` on the top-trailing corner to instantly add a snoozed low:
This PR also fixes the preview in `AddLowButton.swift` that was missing some environment objects.

feat: add button to easily snooze a low

---

OpenGluck/AppIntents/AppsShortcuts.swift
OpenGluck/AppIntents/OpenGluckAppIntents.swift

- add snooze low app intent
- improve dialog text so that it is more inline with Apple's (verb at the end of the sentance)
- fix some icons in the low app intent

feat: improve app intents

---

OpenGluck/AppIntents/OpenGluckAppIntents.swift

Try to improve the phrases Siri says, to be more inline with Apple's:
- “Segment 1. Marked.”
- “Insulin 1 unit. Noted.”

feat: improve AppIntent dialogs

---

OpenGluck/Bricks/AddLowBrick.swift

Add direct button to snooze a low

feat: add snoze Low button

---

OpenGluck/Records/Glucose/CurrentDataGauge.swift

Sometimes the values changes too soon, and the old code wasn't able to handle it.

fix: animation being glitchy when values changes before the animation end

---

OpenGluck/UI/CheckConnectionHasClient.swift

iOS 18 brings some subtleties that need to be cared of in order to maintain compatibility .

fix: iOS 18, Catalyst support

---

OpenGluck Phone App/PhoneAppDelegate.swift

Add support for LOW notifications

feat: add support for LOW notification category

---

OG-Mac-Info.plist

fix: missing OG-Mac-Info.plist
